#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 'I' 'II' 'III' 'IV' 'V' 'VI' 'VII' 'VIII'

bspc config border_width          1
bspc config window_gap            14

bspc config split_ratio           0.52
bspc config borderless_monocle    false
bspc config gapless_monocle       true
bspc config paddingless_monocle   true
bspc config single_monocle        true
bspc config focus_follows_pointer true


bspc config focused_border_color "#d0b4d9"
bspc config normal_border_color "#3e3042"
bspc config active_border_color "#8d7d91"
bspc config presel_feedback_color "#201b21"

bspc rule -a Emacs desktop='^4' follow=on focus=on
bspc rule -a Brave desktop='^2' follow=on focus=on

bspc rule -a Blueman-manager state=floating focus=on follow=on
bspc rule -a kitty state=floating focus=on follow=on
bspc rule -a Pavucontrol state=floating focus=on follow=on
bspc rule -a Pcmanfm state=floating follow=on focus=on manage=off



# Fix cursor
xsetroot -cursor_name left_ptr

#background

#xwall
#feh --bg-scale --no-fehbg --random $(xdg-user-dir)/.config/wallpaper/xwall

#dark
feh --bg-scale --no-fehbg --random $(xdg-user-dir)/.config/wallpaper/dark

#polybar
$HOME/.config/polybar/launch.sh

#picom
picom --experimental-backend

# polkit agent
killall -9 /usr/lib/xfce-polkit/xfce-polkit

/usr/lib/xfce-polkit/xfce-polkit &

#Notification Demon
dunst
