#! /bin/sh

#colors
focused="$(cat ~/.config/bspwm/colors/colorsrc | head -n 1 | tail -n 1)"
normal="$(cat ~/.config/bspwm/colors/colorsrc | head -n 2 | tail -n 1)"
active="$(cat ~/.config/bspwm/colors/colorsrc | head -n 3 | tail -n 1)"
presel="$(cat ~/.config/bspwm/colors/colorsrc | head -n 4 | tail -n 1)"
urgent="$(cat ~/.config/bspwm/colors/colorsrc | head -n 5 | tail -n 1)"
border="$(cat ~/.config/bspwm/colors/colorsrc | head -n 6 | tail -n 1)"

bspc monitor -d 'I' 'II' 'III' 'IV' 'V' 'VI' 'VII' 'VIII'

bspc config border_width          $border
bspc config top_padding           35
bspc config bottom_padding        12
bspc config left_padding          10
bspc config right_padding         10
bspc config window_gap            24
bspc config split_ratio           0.5


bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config paddingless_monocle   true
bspc config single_monocle        false
bspc config focus_follows_pointer true

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner



bspc config focused_border_color      $focused
bspc config normal_border_color       $normal
bspc config active_border_color       $active
bspc config presel_feedback_color     $presel
bspc config urgent_border_color       $urgent


bspc rule -a Emacs           desktop='^1'  state=fullscreen    follow=on   focus=on  manage=on
bspc rule -a Brave-browser   desktop='^2'  state=tiled         follow=on   focus=on  manage=on
bspc rule -a Firefox         desktop='^2'  state=tiled         follow=on   focus=on  manage=on
bspc rule -a mpv             desktop='^5'  state=fullscreen    follow=on   focus=on  manage=on
bspc rule -a feh             desktop='^5'  state=fullscreen    follow=on   focus=on  manage=on
bspc rule -a Sxiv            desktop='^5'  state=fullscreen    follow=on   focus=on  manage=on


bspc rule -a kitty           state=floating  focus=on  follow=on  manage=on
bspc rule -a Blueman-manager state=floating  focus=on  follow=on  manage=on  sticky=on 
bspc rule -a Pavucontrol     state=floating  focus=on  follow=on  manage=on  sticky=on 
bspc rule -a Spacefm         state=floating  focus=on  follow=on  manage=on

#startups
exec ~/.config/bspwm/scripts/startup.sh

