#! /bin/sh
bspc monitor -d 'I' 'II' 'III' 'IV' 'V' 'VI' 'VII' 'VIII'

bspc config border_width          0
bspc config top_padding           10
bspc config bottom_padding        10
bspc config left_padding          10
bspc config right_padding         10
bspc config window_gap            14
bspc config split_ratio           0.5

bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config paddingless_monocle   true
bspc config single_monocle        false
bspc config focus_follows_pointer true

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner



bspc config focused_border_color      "#ffffff"
bspc config normal_border_color       "#ff00ff"
bspc config active_border_color       "#00ff00"
bspc config presel_feedback_color     "#000000"
bspc config urgent_border_color       "#dd2727"


bspc rule -a Emacs           desktop='^1'  state=fullscreen    follow=on   focus=on  manage=on
bspc rule -a Brave-browser   desktop='^2'  state=tiled         follow=on   focus=on  manage=on
bspc rule -a Firefox         desktop='^2'  state=tiled         follow=on   focus=on  manage=on
bspc rule -a mpv             desktop='^5'  state=fullscreen    follow=on   focus=on  manage=on
bspc rule -a Sxiv            desktop='^5'  state=fullscreen    follow=on   focus=on  manage=on


bspc rule -a kitty           state=floating  focus=on  follow=on  manage=on
bspc rule -a Blueman-manager state=floating  focus=on  follow=on  manage=on  sticky=on 
bspc rule -a Pavucontrol     state=floating  focus=on  follow=on  manage=on  sticky=on 
bspc rule -a Spacefm         state=floating  focus=on  follow=on  manage=on
bspc rule -a feh             state=floating    follow=on   focus=on  manage=on

#startups
exec ~/.config/bspwm/scripts/startup.sh
