#! /bin/sh

#colors
focused="$(cat ~/.config/bspwm/misk/bin | head -n 4 | tail -n 1)"
normal="$(cat ~/.config/bspwm/misk/bin | head -n 6 | tail -n 1)"
active="$(cat ~/.config/bspwm/misk/bin | head -n 8 | tail -n 1)"
presel="$(cat ~/.config/bspwm/misk/bin | head -n 10 | tail -n 1)"
urgent="$(cat ~/.config/bspwm/misk/bin | head -n 12 | tail -n 1)"
#gaping
border_width="$(cat ~/.config/bspwm/misk/bin | head -n 15 | tail -n 1)"
top_padding="$(cat ~/.config/bspwm/misk/bin | head -n 17 | tail -n 1)"
bottom_padding="$(cat ~/.config/bspwm/misk/bin | head -n 19 | tail -n 1)"
left_padding="$(cat ~/.config/bspwm/misk/bin | head -n 21 | tail -n 1)"
right_padding="$(cat ~/.config/bspwm/misk/bin | head -n 23 | tail -n 1)"
window_gap="$(cat ~/.config/bspwm/misk/bin | head -n 25 | tail -n 1)"
split_ratio="$(cat ~/.config/bspwm/misk/bin | head -n 27 | tail -n 1)"

bspc monitor -d 'I' 'II' 'III' 'IV' 'V' 'VI' 'VII' 'VIII'

bspc config border_width          $border_width
bspc config top_padding           $top_padding
bspc config bottom_padding        $bottom_padding
bspc config left_padding          $left_padding
bspc config right_padding         $right_padding
bspc config window_gap            $window_gap
bspc config split_ratio           $split_ratio


bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config paddingless_monocle   true
bspc config single_monocle        false
bspc config focus_follows_pointer true

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner



bspc config focused_border_color      $focused
bspc config normal_border_color       $normal
bspc config active_border_color       $active
bspc config presel_feedback_color     $presel
bspc config urgent_border_color       $urgent


bspc rule -a Emacs           desktop='^1'  state=fullscreen    follow=on   focus=on  manage=on
#bspc rule -a Brave-browser   desktop='^2'  state=tiled         follow=on   focus=on  manage=on
bspc rule -a Firefox         desktop='^2'  state=tiled         follow=on   focus=on  manage=on
bspc rule -a mpv             desktop='^5'  state=fullscreen    follow=on   focus=on  manage=on
#bspc rule -a feh             desktop='^5'  state=fullscreen    follow=on   focus=on  manage=on
bspc rule -a feh               state=floating    follow=on   focus=on  manage=on
bspc rule -a Sxiv            desktop='^5'  state=fullscreen    follow=on   focus=on  manage=on


bspc rule -a kitty           state=floating  focus=on  follow=on  manage=on
bspc rule -a Blueman-manager state=floating  focus=on  follow=on  manage=on  sticky=on 
bspc rule -a Pavucontrol     state=floating  focus=on  follow=on  manage=on  sticky=on 
bspc rule -a Spacefm         state=floating  focus=on  follow=on  manage=on

#startups
exec ~/.config/bspwm/scripts/startup.sh

