#!/bin/bash
#colors
#focused_border_color
#ffffff
#normal_border_color
#00ff00ff
#active_border_color
#00ff00
#presel_feedback_color
#000000
#urgent_border_color
#dd2727

#border_width
0
#top_padding
35
#bottom_padding
12
#left_padding  
10
#right_padding 
15
#window_gap    
33
#split_ratio
0.5

